# numpy 연습문제

In [ ]:
import numpy as np

## 1. 10개의 0 벡터를 만들고 4번째와 5번째 Index의 값을 1로 한 후 (5,2) 행렬로 만들어라

In [ ]:
arr1 = np.zeros(10)
# arr1[[4, 5]] = 1
arr1[4:6] = 1
arr1.reshape(5, 2)


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

## 2. 10에서 30까지 2씩 증가하는 vector를 만들고 다음 list와 요소별 사칙연산(+, -, *, /)을 하여라
##### a = [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]

In [ ]:
arr1 = np.arange(10, 30, 2)
a = np.array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

print(arr1 + a)
print(arr1 - a)
print(arr1 * a)
print(arr1 / a)

[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]


In [ ]:
arr1.shape

(10,)

## 3.  <1에서 100>까지 10개를 균등하게 분할하여 배열을 만들고,  각각의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱을 구하여라

In [ ]:
arr1 = np.linspace(1, 100, 10)
print(arr1.sum())
print(arr1.mean())
print(arr1.std())
print(arr1.var())
print(arr1.min())
print(arr1.max())
print(arr1.cumsum())
print(arr1.cumprod())

505.0
50.5
31.595094555959157
998.25
1.0
100.0
[  1.  13.  36.  70. 115. 171. 238. 316. 405. 505.]
[1.00000000e+00 1.20000000e+01 2.76000000e+02 9.38400000e+03
 4.22280000e+05 2.36476800e+07 1.58439456e+09 1.23582776e+11
 1.09988670e+13 1.09988670e+15]


## 4.  0에서 10까지 random한 값을 지닌 3x3 실수 행렬을 만들어라

In [ ]:
np.random.seed(42)
arr1 = np.random.rand(3,3)
arr2 = arr1 * 10
arr2

array([[3.74540119, 9.50714306, 7.31993942],
       [5.98658484, 1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012]])

## 5.  0에서 10까지 random한 값을 지닌 3x3 정수 행렬을 만들어라

In [ ]:
np.random.randint(0, 10, (3,3))

array([[8, 2, 4],
       [2, 6, 4],
       [8, 6, 1]])


## 6. 5x2 행렬을 만들고 Standardization(정규화 하여라)
- standardization: (x - mean(x))/std(x)
- mean과 std는 Row단위로 연산을 해야함.(return shape이 (2,))
- 전체 결과는 5x2 행렬

In [84]:
arr1 = np.linspace(-1000, 1000, 5)
arr2 = np.linspace(0, 10, 5)

arr1 = arr1.reshape(5, -1)
arr2 = arr2.reshape(5, -1)
arr3 = np.concatenate((arr1, arr2), axis=1)
arr3

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [83]:
arr1.std(), arr2.std()

(707.1067811865476, 3.5355339059327378)

In [90]:
arr4 = (arr3 - arr3.mean(axis=0)) / arr3.std(axis=0)
arr4

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [91]:
arr4.mean(), arr4.std(), arr4.var()

(0.0, 0.9999999999999999, 0.9999999999999998)

# 7. 5x2 행렬을 만들고 Min-Max정규화(Nomalization) 하여라
- (x - min(x)) / (max(x) - min(x))
- Row단위로 연산. (return shape)
- mean과 std는 Row단위로 연산을 해야함.(return shape이 (2,))
- 전체 결과는 5x2 행렬

In [92]:
arr3

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [94]:
arr5 = (arr3-arr3.min(axis=0)) / (arr3.max(axis=0) - arr3.min(axis=0))
arr5

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])