In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.array([0.1, 0.2, 0.3])
arr2

array([0.1, 0.2, 0.3])

In [6]:
arr3 = np.array(['a', 'b', 'c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
arr4 = np.array([1, 2, 'a', 'b', 0.1, 0.2])
arr4

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [11]:
arr5 = np.array([1, 2, 0.3, 0.4])
arr5

array([1. , 2. , 0.3, 0.4])

In [13]:
arr6 = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## array의 타입

In [14]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1.dtype

dtype('int32')

In [17]:
arr2

array([0.1, 0.2, 0.3])

In [18]:
arr2.dtype

dtype('float64')

In [20]:
print(arr3.dtype)
arr3

<U1


array(['a', 'b', 'c'], dtype='<U1')

In [21]:
print(arr4.dtype)
arr4

<U11


array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [22]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.3, 0.4])

### shape
- 배열의 형태

In [29]:
arr5

array([1. , 2. , 0.3, 0.4])

In [30]:
arr5.shape

(4,)

In [31]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr6.shape

(3, 3)

## arange

In [33]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr2 = np.arange(3, 13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
arr3 = np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [37]:
arr4 = np.arange(3, 100, 3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

### linspace

In [40]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### reshape(배열의 형태 변환)

In [41]:
arr = np.arange(36.0)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [43]:
arr.shape

(36,)

In [44]:
arr2 = arr.reshape(12, 3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [45]:
arr2.shape

(12, 3)

In [46]:
# 3 dimension
arr3 = arr.reshape(3, 4, 3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [48]:
print(arr1.shape)
arr1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr1.shape = (5, 2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
# -1 shape
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [56]:
arr3.reshape(-1, 12)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [57]:
arr3.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [58]:
arr3.reshape(4, -1, 3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

### astype - 배열의 dtype 변환

In [60]:
arr1 = np.arange(5)
arr2 = np.arange(0.0, 0.5,0.1)
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [61]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [65]:
# int -> float
print(arr1.astype(float))
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [67]:
# float -> char
print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


## random

#### rand

In [68]:
np.random.rand(5)

array([0.03477005, 0.50645271, 0.01662368, 0.77290003, 0.41725696])

In [70]:
np.random.rand(3, 3)

array([[0.43889655, 0.9733667 , 0.78129591],
       [0.73785237, 0.61011458, 0.65739288],
       [0.4235701 , 0.17747677, 0.27694163]])

In [71]:
np.random.rand(2, 2, 2)

array([[[0.89298348, 0.12696011],
        [0.4990017 , 0.19082158]],

       [[0.79959712, 0.6485867 ],
        [0.45921517, 0.61974912]]])

#### randint

In [74]:
np.random.randint(-5, 3, (3,3))

array([[ 2, -3, -3],
       [-5,  1, -4],
       [-4,  0, -3]])

#### randn

In [76]:
np.random.randn(2, 5)

array([[-0.36439866, -1.69896187,  0.35071311, -0.07008234,  0.56087062],
       [ 3.44683073,  0.11971436,  0.08987083, -2.50444343, -0.74657595]])

## array의 indexing, Slicing

In [79]:
arr1 = np.arange(0, 100, 10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [82]:
arr1[0], arr1[-1], arr1[5]

(0.0, 90.0, 50.0)

In [83]:
arr1[:], arr1[4:], arr1[1:8]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70.]))

In [84]:
arr1[::2], arr1[::3]

(array([ 0., 20., 40., 60., 80.]), array([ 0., 30., 60., 90.]))

#### n-Dim Array Indexing, Slicing

In [89]:
# 2차원 배열: 0~23까지 차례로 (8, 3)의 배열을 만드세요. dtype=float
arr2 = np.arange(24.0).reshape(8, 3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [92]:
arr2[0], arr2[4]

(array([0., 1., 2.]), array([12., 13., 14.]))

In [99]:
print(arr2[3][1]) # 성능이 조금 느려요.
print(arr2[3, 1]) # Standard Case on Numpy

10.0
10.0


In [104]:
print(arr2[3, 1:])
print(arr2[3:, 1:])
print(arr2[::2, :])

[10. 11.]
[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [107]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [113]:
print(arr2[[0, 5, 3]])
print('-'* 10)
print(arr2[[0, 5, 3], [1]])
print("-"* 10)

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
----------
[ 1. 16. 10.]
----------


In [116]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [117]:
arr2 > 10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [119]:
arr2[arr2>10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [120]:
arr2[arr2%2==1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

#### numpy의 상수

In [125]:
arr = np.array([1, 2, 3, np.nan, np.inf, -np.inf])
print("dtype: ", arr.dtype)
arr

dtype:  float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

## arr의 연산

In [128]:
arr1 = np.arange(0, 10, 1)
arr2 = np.arange(1, 0, -0.1)
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [129]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
# array 와 scalar 연산
arr1 + 1, arr1 + [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [134]:
print(arr1 - 1)
print(arr1 * 10)
print(arr1 / 10)
print(arr1 ** 2)
print(arr1 % 2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [135]:
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [136]:
arr1 + arr2

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [139]:
print(arr1 - arr2)
print(arr1 ** arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[-1.   0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9]
[0.         1.         1.74110113 2.15766928 2.29739671 2.23606798
 2.04767251 1.79278996 1.51571657 1.24573094]
[0.  0.9 1.6 2.1 2.4 2.5 2.4 2.1 1.6 0.9]
[ 0.          1.11111111  2.5         4.28571429  6.66666667 10.
 15.         23.33333333 40.         90.        ]
[0.  0.1 0.4 0.2 0.4 0.5 0.4 0.1 0.2 0.1]


In [141]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [142]:
arr1 > arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

In [144]:
# 0행렬
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [145]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 일행렬

In [146]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [147]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 단위행렬

In [149]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [150]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [152]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 통계를 위한 연산

In [154]:
arr1 = np.arange(1, 11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

##### sum 

In [156]:
arr1.sum()

55.0

In [158]:
arr1.sum(axis=0)

array([25., 30.])

In [159]:
arr1.sum(axis=1)

array([ 3.,  7., 11., 15., 19.])

##### mean

In [160]:
arr1.mean()

5.5

In [161]:
arr1.mean(axis=0)

array([5., 6.])

In [162]:
arr1.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

##### var

In [163]:
arr1.var()

8.25

In [164]:
arr1.var(axis=0)

array([8., 8.])

In [165]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

##### std 

In [166]:
arr1.std()

2.8722813232690143

In [167]:
arr1.std(axis=0)

array([2.82842712, 2.82842712])

In [168]:
arr1.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

##### min

In [179]:
print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))


1.0
[1. 2.]
[1. 3. 5. 7. 9.]


##### max

In [180]:
arr1.max(axis=0)

array([ 9., 10.])

In [181]:
arr1.max(axis=1)

array([ 2.,  4.,  6.,  8., 10.])

##### cumsum 

In [182]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [183]:
arr1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

In [184]:
arr1.cumsum(axis=0)

array([[ 1.,  2.],
       [ 4.,  6.],
       [ 9., 12.],
       [16., 20.],
       [25., 30.]])

In [185]:
arr1.cumsum(axis=1)

array([[ 1.,  3.],
       [ 3.,  7.],
       [ 5., 11.],
       [ 7., 15.],
       [ 9., 19.]])

##### cumprod 

In [186]:
arr1.cumprod()

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])

In [187]:
arr1.cumprod(axis=0)

array([[1.00e+00, 2.00e+00],
       [3.00e+00, 8.00e+00],
       [1.50e+01, 4.80e+01],
       [1.05e+02, 3.84e+02],
       [9.45e+02, 3.84e+03]])

#### sqrt, log, exp

In [169]:
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [170]:
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [173]:
print(np.exp(arr1).dtype)
np.exp(arr1)

float64


array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [175]:
2.5e+3

2500.0

In [176]:
2.5e-2

0.025

## 행렬연산

In [199]:
arr1 = np.arange(1, 7).astype(np.float64).reshape(2, 3)
arr2 = np.arange(6, 0, -1.0).astype(np.float64).reshape(3,2)
arr1, arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [200]:
arr1.shape, arr2.shape

((2, 3), (3, 2))

In [201]:
arr1 @ arr2

array([[20., 14.],
       [56., 41.]])

In [203]:
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [205]:
np.matmul(arr1, arr2)

array([[20., 14.],
       [56., 41.]])

##### 전치 

In [207]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [211]:
arr3 = np.arange(6).reshape(2, 3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [212]:
arr1.shape, arr3.shape

((2, 3), (2, 3))

In [214]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [216]:
arr3.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [217]:
arr1.dot(arr3.T)

array([[ 8., 26.],
       [17., 62.]])

## 역행렬

In [220]:
arr1 = np.arange(1, 5).reshape(2, 2)
arr1

array([[1, 2],
       [3, 4]])

In [222]:
arr2 = np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [224]:
arr1.dot(arr2)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [227]:
arr2.dot(arr1)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

## concat

In [230]:
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(0, 40, 10).reshape(2,2)
arr1, arr2

(array([[0, 1],
        [2, 3]]),
 array([[ 0, 10],
        [20, 30]]))

In [234]:
np.concatenate((arr1, arr2), axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [236]:
np.concatenate((arr1, arr2), axis=1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

In [238]:
# np.c_
np.c_[arr1, arr2]

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])