In [33]:
import numpy as np
import tensorflow as tf
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense,Flatten,Embedding

docs = ['너무 재미있네요','최고예요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한번 더 보고싶네요','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

x=tokenizer.texts_to_sequences(docs)
padded_x = pad_sequences(x,4)
word_size = len(tokenizer.word_index)+1
print("\n패딩결과\n",padded_x)

model = Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
history = model.fit(padded_x,cla,epochs=20)
print('\n Accuracy: %.4f'%model.evaluate(padded_x,cla)[1])

{'너무': 1, '재미있네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

패딩결과
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


C:\ProgramData\Anaconda3\envs\tf_V2\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/20
10/10 [==============================] - 0s 14ms/step - loss: 0.6953 - accuracy: 0.5000
Epoch 2/20
10/10 [==============================] - 0s 200us/step - loss: 0.6934 - accuracy: 0.5000
Epoch 3/20
10/10 [==============================] - 0s 320us/step - loss: 0.6914 - accuracy: 0.6000
Epoch 4/20
10/10 [==============================] - 0s 290us/step - loss: 0.6894 - accuracy: 0.6000
Epoch 5/20
10/10 [==============================] - 0s 196us/step - loss: 0.6874 - accuracy: 0.6000
Epoch 6/20
10/10 [==============================] - 0s 299us/step - loss: 0.6854 - accuracy: 0.6000
Epoch 7/20
10/10 [==============================] - 0s 221us/step - loss: 0.6835 - accuracy: 0.6000
Epoch 8/20
10/10 [==============================] - 0s 215us/step - loss: 0.6816 - accuracy: 0.7000
Epoch 9/20
10/10 [==============================] - 0s 200us/step - loss: 0.6796 - accuracy: 0.7000
Epoch 10/20
10/10 [==============================] - 0s 184us/step - loss: 0.6776 - accuracy: 0.8000


In [34]:
model.predict_classes(padded_x)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [35]:
model.predict(padded_x)

array([[0.50227416],
       [0.5049155 ],
       [0.53424525],
       [0.51090115],
       [0.51673996],
       [0.47681367],
       [0.4815502 ],
       [0.4757123 ],
       [0.46908125],
       [0.47411224]], dtype=float32)