In [2]:
text = '해보지 않으면 해낼 수 없다.'
from keras.preprocessing.text import text_to_word_sequence
from keras.preprocessing.text import Tokenizer

result = text_to_word_sequence(text)
result
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_counts)

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


# tokenizer함수
  ###
    text_to_word_sequence(text) : 단어단위로
  ### Tokenizer 함수
    0.fit_on_texts(list) : 문장에 토큰화 함수 적용
    
    1.word_counts : 단어의 빈도수 [(),(),()]

    2.document_count : 문서수

    3.word_docs : 단어들이 몇개의 문서에 나오느냐

    4.word_index : 단어의 고유 인덱스   -->딕셔너리
    
    5.texts_to_sequences(list) : 인덱스로 채워진 배열
  ### OneHot Encoding
    fit_on_texts   -->    temp = texts_to_sequences   ->>to_categorical

In [3]:
tokenizer.word_counts

OrderedDict([('먼저', 1),
             ('텍스트의', 2),
             ('각', 1),
             ('단어를', 1),
             ('나누어', 1),
             ('토큰화합니다', 1),
             ('단어로', 1),
             ('토큰화해야', 1),
             ('딥러닝에서', 2),
             ('인식됩니다', 1),
             ('토큰화한', 1),
             ('결과는', 1),
             ('사용할', 1),
             ('수', 1),
             ('있습니다', 1)])

In [4]:
tokenizer.document_count

3

In [5]:
tokenizer.word_docs

defaultdict(int,
            {'토큰화합니다': 1,
             '먼저': 1,
             '나누어': 1,
             '각': 1,
             '단어를': 1,
             '텍스트의': 2,
             '딥러닝에서': 2,
             '단어로': 1,
             '인식됩니다': 1,
             '토큰화해야': 1,
             '결과는': 1,
             '있습니다': 1,
             '토큰화한': 1,
             '수': 1,
             '사용할': 1})

In [6]:
tokenizer.word_index

{'텍스트의': 1,
 '딥러닝에서': 2,
 '먼저': 3,
 '각': 4,
 '단어를': 5,
 '나누어': 6,
 '토큰화합니다': 7,
 '단어로': 8,
 '토큰화해야': 9,
 '인식됩니다': 10,
 '토큰화한': 11,
 '결과는': 12,
 '사용할': 13,
 '수': 14,
 '있습니다': 15}

In [12]:
from keras.preprocessing.text import Tokenizer
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다.'
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print(tokenizer.word_index)

x = tokenizer.texts_to_sequences([text])
print(x)

from keras.utils import to_categorical
word_size = len(tokenizer.word_index)+1
x=to_categorical(x,num_classes=word_size)

print(x)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}
[[1, 2, 3, 4, 5, 6]]
[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [8]:
x = tokenizer.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [10]:
from keras.utils import to_categorical
word_size = len(tokenizer.word_index)+1
x=to_categorical(x,num_classes=word_size)

print(x)

[[[[1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
  

In [38]:
from keras.layers import Embedding,Flatten,Dense
from keras.models import Sequential
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

In [39]:
docs= ['너무 재미있네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

from keras.preprocessing.text import text_to_word_sequence,Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

{'너무': 1, '재미있네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [40]:
from keras.layers import Embedding,Flatten,Dense
from keras.models import Sequential
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

docs= ['너무 재미있네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

from keras.preprocessing.text import text_to_word_sequence,Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

x = tokenizer.texts_to_sequences(docs)
print(x)
padding_size = max(x)
padded_x = pad_sequences(x,4)
print(padded_x)

from keras.layers import Embedding,Flatten,Dense
from keras.models import Sequential
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

docs= ['너무 재미있네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

from keras.preprocessing.text import text_to_word_sequence,Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

x = tokenizer.texts_to_sequences(docs)
print(x)
padding_size = max(x)
padded_x = pad_sequences(x,4)
print(padded_x)

word_size = len(tokenizer.word_index)+1
model=Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
history = model.fit(padded_x,cla,epochs=20)
print('\n Accuracy: %.4f'%model.evaluate(padded_x,cla)[1])

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]
[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [50]:
from keras.layers import Embedding,Flatten,Dense
from keras.models import Sequential
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

docs= ['너무 재미있네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

from keras.preprocessing.text import text_to_word_sequence,Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

x = tokenizer.texts_to_sequences(docs)
print(x)
padding_size = max(x)
padded_x = pad_sequences(x,4)
print(padded_x)

word_size = len(tokenizer.word_index)+1
model=Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
history = model.fit(padded_x,cla,epochs=20)
print('\n Accuracy: %.4f'%model.evaluate(padded_x,cla)[1])

{'너무': 1, '재미있네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}
[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]
[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


C:\ProgramData\Anaconda3\envs\tf_V2\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/20
10/10 [==============================] - 0s 29ms/step - loss: 0.6980 - accuracy: 0.5000
Epoch 2/20
10/10 [==============================] - 0s 197us/step - loss: 0.6964 - accuracy: 0.5000
Epoch 3/20
10/10 [==============================] - 0s 497us/step - loss: 0.6943 - accuracy: 0.5000
Epoch 4/20
10/10 [==============================] - 0s 154us/step - loss: 0.6924 - accuracy: 0.5000
Epoch 5/20
10/10 [==============================] - 0s 462us/step - loss: 0.6904 - accuracy: 0.5000
Epoch 6/20
10/10 [==============================] - 0s 200us/step - loss: 0.6883 - accuracy: 0.5000
Epoch 7/20
10/10 [==============================] - 0s 598us/step - loss: 0.6861 - accuracy: 0.5000
Epoch 8/20
10/10 [==============================] - 0s 259us/step - loss: 0.6840 - accuracy: 0.6000
Epoch 9/20
10/10 [==============================] - 0s 241us/step - loss: 0.6819 - accuracy: 0.7000
Epoch 10/20
10/10 [==============================] - 0s 378us/step - loss: 0.6798 - accuracy: 0.8000


In [48]:
model.predict_classes(padded_x)

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [51]:
model.predict(padded_x)

array([[0.50584817],
       [0.5056755 ],
       [0.5367472 ],
       [0.5483807 ],
       [0.506868  ],
       [0.4849587 ],
       [0.47540092],
       [0.47784096],
       [0.48827127],
       [0.48653167]], dtype=float32)

In [ ]:
from keras.layers import Embedding,Flatten,Dense
from keras.models import Sequential
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

docs= ['너무 재미있네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

from keras.preprocessing.text import text_to_word_sequence,Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

x = tokenizer.texts_to_sequences(docs)
print(x)
padding_size = max(x)
padded_x = pad_sequences(x,4)
print(padded_x)

from keras.layers import Embedding,Flatten,Dense
from keras.models import Sequential
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

docs= ['너무 재미있네요','최고에요','참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']
cla = np.array([1,1,1,1,1,0,0,0,0,0])

from keras.preprocessing.text import text_to_word_sequence,Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(tokenizer.word_index)

x = tokenizer.texts_to_sequences(docs)
print(x)
padding_size = max(x)
padded_x = pad_sequences(x,4)
print(padded_x)

word_size = len(tokenizer.word_index)+1
model=Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
history = model.fit(padded_x,cla,epochs=20)
print('\n Accuracy: %.4f'%model.evaluate(padded_x,cla)[1])